# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.PersonalData.io
title: PersonalData.IO
email: GetMy@PersonalData.IO
author: John Doe
description: > # "PersonalData.IO helps you reclaim your personal data and your privacy from corporations. Our automated and intelligent assistants work for you pro bono to defend your rights, and interact with corporate lawyers on your behalf."
copyright: 'Copyright 2016 PersonalData.IO. All Rights Reserved.'
credits: 'Credits: PersonalData.IO, icon by Lisa Staudinger'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/PersonalDataIO
  - title: github
    icon: github
    url: https://github.com/PersonalDataDotIO
  - title: email
    icon: envelope
    url: mailto:GetMy@PersonalData.IO?subject=PersonalData.IO contact&body=Hi,I found your website and...
